CREATE DATABASE customer_behavior;
USE customer_behavior;
SELECT * FROM customer;


-- Q1. What is the total revenue generated by male vs. female 
SELECT gender, sum(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >=
(SELECT avg(purchase_amount) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amt
FROM customer
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend, 
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

SELECT MIN(previous_purchases) FROM customer;


-- Q7. Segment customers into New, Returning, and Loyal
-- based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer
)

SELECT customer_segment, COUNT(*) AS no_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue ;


-- Q11. Do customers with higher review ratings tend to make more repeat purchases and spend more,
-- compared to customers with lower ratings?
SELECT
    CASE
        WHEN review_rating < 3 THEN 'Low (below 3)'
        WHEN review_rating >= 3 AND review_rating < 4 THEN 'Medium (3 to 3.9)'
        ELSE 'High (4 and above)'
    END AS rating_band,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(previous_purchases),2) AS avg_previous_purchases,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer
GROUP BY rating_band
ORDER BY avg_previous_purchases DESC;


-- Q12. Do customers who use discounts end up with more previous purchases
-- (are discounts building loyalty), or do discount users and non-users look the same?
SELECT
    discount_applied,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(previous_purchases),2) AS avg_previous_purchases,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer
GROUP BY discount_applied;


-- Q13. Does spending or order volume change by season — is there a seasonal pattern to purchases?
SELECT
    season,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;


-- Q14. Does payment method used relate to 
-- how much customers spend or how loyal they are?
SELECT
    payment_method,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
    ROUND(AVG(previous_purchases),2) AS avg_previous_purchases
FROM customer
GROUP BY payment_method
ORDER BY avg_purchase_amount DESC;
